### PR TITLE
add support for table (with tbody), tr, th, td tags

### PR DESCRIPTION
**Pull request by sauerbraten**

### CODE REVIEW

**Comment by hanspagel** [comment]
Crazy. Thank you @sauerbraten!

**Comment by hanspagel** [comment]
Tagged as 0.5.1

**Comment by hanspagel** [comment]
Added you to the README as a contributor 🎉

**Comment by sauerbraten** [comment]
Great to have this merged so quickly! For consistency between the two conversions how about this one, too? https://github.com/scrumpy/prosemirror-to-html/pull/11 :)

**Pull request merged**
